### Util scripts

# Imports
#
import os
import subprocess
from collections import defaultdict
from datetime import datetime, timezone

######################################
# Read params from sys_param #
######################################

### Parse the charge/params from sys_param.str
def parse_param(sys_param):
    """
    Parse the params from sys_param.str file such as charge, box size, units
    """
    param_dict = defaultdict(str)
    f  = open(sys_param , 'r').readlines()
    for line in f:
        line = line.split()
        param_dict[str(line[1]).lower()] = line[3]

    #    print(param_dict)
    return(param_dict)

#############################
# Manipulate template files #
#############################
def replace_resname(resname, template_file, output_file):
    """
    Copy template file to new and replace the resname in file with desired resname.
    Made this mostly to add correct ions to system.
    """
    # Call sed to replace the XXX with 3-letter resname
    # TODO
    # expand the replacemenet from 3-letter XXX to any length of XXX's
    # Also give better names
    template_text = open(template_file, 'r').read()
    replaced_text = template_text.replace('XXX', resname)
    with open(output_file, 'w') as f:
        f.write(replaced_text)
    f.close()
    return(f"Replaced with {resname}.")

##########################
# Write the packmol input #
##########################

def write_pack_inp(ncharge, counter_ion, ion_dist ): # How many counter ions and the dist
    output_file="box_ion.inp"
    with open(output_file, 'w') as f:
        f.write(f"## Packmol input template \n")
        f.write(f"\n")
        f.write(f"## Add {counter_ion} to the system\n")
        f.write(f"\n")
        f.write(f"tolerance 2.0\n")
        f.write(f"\n")
        f.write(f"filetype pdb\n")
        f.write(f"resnumbers 0\n")
        f.write(f"\n")
        f.write(f"##Place molecule/system after recenter\n")
        f.write(f"structure recenter.pdb\n")
        f.write(f"  number 1\n")
        f.write(f"  inside box -10.00 -10.00 -10.00 10.00 10.00 10.00\n")
        f.write(f"end structure\n")
        f.write(f"\n")
        f.write(f"##Place counter-ions\n")
        f.write(f"structure {counter_ion.upper()}.pdb\n")
        f.write(f"  number {ncharge}\n")
        f.write(f"  outside sphere 0.0 0.0 0.0 20.0 \n") # OVER_HERE
        f.write(f"  inside box -25.0 -25.0 -25.0 25.0 25.0 25.0\n")
        f.write(f"end structure\n")
        f.write(f"\n")
        f.write(f"## Write the output box\n")
        f.write(f"output box_ion.pdb\n")
    return("Wrote packmol input to add counter-ion.")


#####################
# CHARMM inp files #
#####################

### Writing a CHARMM input file
### Write the mol recenter script
def write_recenter_inp():
    output_file = "recenter.inp"

    with open(output_file, 'w') as inp:
        # Get username
        user = os.getenv('USERNAME') or os.getenv('USER')
        # Get current UTC date and time
        current_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")

        inp.write(f"* GENERATED BY SYSGEN\n")
        inp.write(f"* THIS IS TO RECENTER THE SYS AND GET CHARMM COMPATIBLE PDB/PSF/CRD\n")
        #        inp.write(f"* Made by {user} on {current_utc}\n")
        inp.write(f"* \n")
        inp.write(f"\n")
        inp.write(f"DIMENS CHSIZE 2000000\n")
        inp.write(f"!DIMENS CHSIZE 5000000 MAXRES 3000000\n")
        inp.write(f"\n")
        inp.write(f"bomlev -3 \n")
        inp.write(f"\n")
        inp.write(f"! Read charmm ff files \n")
        inp.write(f"stream toppar.str \n")
        inp.write(f"\n")
        inp.write(f"! Read in the mol/sys \n")
        inp.write(f"read sequence MGLYOL 1 \n")
        inp.write(f"generate MGLYOL \n")
        inp.write(f"\n")
        inp.write(f"open read unit 90 card name output.crd \n")
        inp.write(f"read coor unit 90 card resid \n")
        inp.write(f"close unit 90\n")
        inp.write(f"\n")
        inp.write(f"define solute sele segid MGLYOL end \n")
        inp.write(f"define SYS sele solute .and. ( .not. hydrogen ) end\n")
        inp.write(f"cons harm absolute force 1.0 sele SYS end \n")
        inp.write(f"\n")
        inp.write(f"COOR STAT\n")
        inp.write(f"COOR TRANSLATE XDIR -?XAVE YDIR -?YAVE ZDIR -?ZAVE\n")
        inp.write(f"\n")
        inp.write(f"open write unit 91 card name recenter.psf \n")
        inp.write(f"write psf card unit 91  \n")
        inp.write(f"close unit 91\n")
        inp.write(f"\n")
        inp.write(f"open write unit 92 card name recenter.crd \n")
        inp.write(f"write coor card unit 92  \n")
        inp.write(f"close unit 92\n")
        inp.write(f"\n")
        inp.write(f"open write unit 93 card name recenter_off.pdb \n")
        inp.write(f"write coor pdb card unit 93 official \n")
        inp.write(f"close unit 93\n")
        inp.write(f"\n")
        inp.write(f"open write unit 93 card name recenter.pdb \n")
        inp.write(f"write coor pdb card unit 93  \n")
        inp.write(f"close unit 93\n")
        inp.write(f"\n")
        inp.write(f"calc cgtot = int ( ?cgtot )\n")
        inp.write(f"open write unit 94 card name sys_param.str\n")
        inp.write(f"write title unit 94\n")
        inp.write(f"* set ncharge = @cgtot ! not ?cgtot\n")
        inp.write(f"*\n")
        inp.write(f"\n")
        inp.write(f"STOP\n")
        inp.close()
    return(f"Recentered and wrote psf/pdb/crd")

## Usage:
#write_recenter_inp()
parse_param("sys_param.str")
