### Util scripts

# Imports
#
import os
import subprocess
from collections import defaultdict
from datetime import datetime, timezone

######################################
# Read params from sys_param #
######################################

### Parse the charge/params from sys_param.str
def parse_param(sys_param):
    """
    Parse the params from sys_param.str file such as charge, box size, units
    """
    param_dict = defaultdict(str)
    f  = open(sys_param , 'r').readlines()
    for line in f:
        line = line.split()
        param_dict[str(line[1]).lower()] = line[3]

    #    print(param_dict)
    return(param_dict)

##########################
# Write the packmol input #
##########################

def write_pack_inp(ncharge, counter_ion, ion_dist , output_file): # How many counter ions and the dist
    with open(output_file, 'w') as f:
        f.write(f"# Packmol input template \n")
        f.write(f"\n")
        f.write(f"Add {counter_ion} to the system\n")
        f.write(f"\n")
        f.write(f"tolerance 2.0\n")
        f.write(f"\n")
        f.write(f"filetype pdb\n")
        f.write(f"resnumbers 0\n")
        f.write(f"\n")
        f.write(f"structure {counter_ion.upper()}.pdb\n")
        f.write(f"  number {ncharge}\n")
        f.write(f"  outside sphere\n") # OVER_HERE
    return("Wrote packmol input.")



#structure cal.pdb
#  number 1
#  inside box -0.00 -0.00 -0.00 0.0 0.0 0.0
#end structure
#
## Place POT ions in the same box 20A
#structure cla.pdb
#  number 2
#  outside sphere 0. 0. 0. 20.
#  inside box -25.0 -25.0 -25.0 25.0 25.0 25.0
#end structure
#
## Write the box pdb
#output cal_cla.pdb

#####################
# CHARMM inp files #
#####################

### Writing a CHARMM input file
### Write the mol recenter script
def write_recenter_inp():
    output_file = "recenter.inp"

    with open(output_file, 'w') as inp:
        # Get username
        user = os.getenv('USERNAME') or os.getenv('USER')
        # Get current UTC date and time
        current_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")

        inp.write(f"* GENERATED BY SYSGEN\n")
        inp.write(f"* THIS IS TO RECENTER THE SYS AND GET CHARMM COMPATIBLE PDB/PSF/CRD\n")
        #        inp.write(f"* Made by {user} on {current_utc}\n")
        inp.write(f"* \n")
        inp.write(f"\n")
        inp.write(f"DIMENS CHSIZE 2000000\n")
        inp.write(f"!DIMENS CHSIZE 5000000 MAXRES 3000000\n")
        inp.write(f"\n")
        inp.write(f"bomlev -3 \n")
        inp.write(f"\n")
        inp.write(f"! Read charmm ff files \n")
        inp.write(f"stream toppar.str \n")
        inp.write(f"\n")
        inp.write(f"! Read in the mol/sys \n")
        inp.write(f"read sequence MGLYOL 1 \n")
        inp.write(f"generate MGLYOL \n")
        inp.write(f"\n")
        inp.write(f"open read unit 90 card name output.crd \n")
        inp.write(f"read coor unit 90 card resid \n")
        inp.write(f"close unit 90\n")
        inp.write(f"\n")
        inp.write(f"define solute sele segid MGLYOL end \n")
        inp.write(f"define SYS sele solute .and. ( .not. hydrogen ) end\n")
        inp.write(f"cons harm absolute force 1.0 sele SYS end \n")
        inp.write(f"\n")
        inp.write(f"COOR STAT\n")
        inp.write(f"COOR TRANSLATE XDIR -?XAVE YDIR -?YAVE ZDIR -?ZAVE\n")
        inp.write(f"\n")
        inp.write(f"open write unit 91 card name recenter.psf \n")
        inp.write(f"write psf card unit 91  \n")
        inp.write(f"close unit 91\n")
        inp.write(f"\n")
        inp.write(f"open write unit 92 card name recenter.crd \n")
        inp.write(f"write coor card unit 92  \n")
        inp.write(f"close unit 92\n")
        inp.write(f"\n")
        inp.write(f"open write unit 93 card name recenter_off.pdb \n")
        inp.write(f"write coor pdb card unit 93 official \n")
        inp.write(f"close unit 93\n")
        inp.write(f"\n")
        inp.write(f"open write unit 93 card name recenter.pdb \n")
        inp.write(f"write coor pdb card unit 93  \n")
        inp.write(f"close unit 93\n")
        inp.write(f"\n")
        inp.write(f"calc cgtot = int ( ?cgtot )\n")
        inp.write(f"open write unit 94 card name sys_param.str\n")
        inp.write(f"write title unit 94\n")
        inp.write(f"* set ncharge = @cgtot ! not ?cgtot\n")
        inp.write(f"*\n")
        inp.write(f"\n")
        inp.write(f"STOP\n")
        inp.close()
    return(f"Recentered and wrote psf/pdb/crd")

## Usage:
#write_recenter_inp()
parse_param("sys_param.str")
